//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QolaMVC.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activite User.
        /// </summary>
        public static string ActiviteUser {
            get {
                return ResourceManager.GetString("ActiviteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity (French).
        /// </summary>
        public static string Activity_fr {
            get {
                return ResourceManager.GetString("Activity_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Category.
        /// </summary>
        public static string ActivityCategory {
            get {
                return ResourceManager.GetString("ActivityCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Category (French).
        /// </summary>
        public static string ActivityCategory_fr {
            get {
                return ResourceManager.GetString("ActivityCategory_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Display Title Ex..
        /// </summary>
        public static string ActivityDisplayTitleEx {
            get {
                return ResourceManager.GetString("ActivityDisplayTitleEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Activity.
        /// </summary>
        public static string AddActivity {
            get {
                return ResourceManager.GetString("AddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Activity Category.
        /// </summary>
        public static string AddActivityCategory {
            get {
                return ResourceManager.GetString("AddActivityCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Allergy.
        /// </summary>
        public static string AddAllergy {
            get {
                return ResourceManager.GetString("AddAllergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Building.
        /// </summary>
        public static string AddBuilding {
            get {
                return ResourceManager.GetString("AddBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Suite.
        /// </summary>
        public static string AddSuite {
            get {
                return ResourceManager.GetString("AddSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Venue.
        /// </summary>
        public static string AddVenue {
            get {
                return ResourceManager.GetString("AddVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy.
        /// </summary>
        public static string Allergy {
            get {
                return ResourceManager.GetString("Allergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy Name.
        /// </summary>
        public static string AllergyName {
            get {
                return ResourceManager.GetString("AllergyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARE YOU SURE YOU WANT TO DELETE THIS RECORD?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteThisRecord {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteThisRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        public static string Back_big {
            get {
                return ResourceManager.GetString("Back_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back_small {
            get {
                return ResourceManager.GetString("Back_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        public static string Breakfast {
            get {
                return ResourceManager.GetString("Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildings.
        /// </summary>
        public static string Buildings {
            get {
                return ResourceManager.GetString("Buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryName (English).
        /// </summary>
        public static string CategoryName_en {
            get {
                return ResourceManager.GetString("CategoryName_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryName (French).
        /// </summary>
        public static string CategoryName_fr {
            get {
                return ResourceManager.GetString("CategoryName_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        public static string Clear_big {
            get {
                return ResourceManager.GetString("Clear_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear_small {
            get {
                return ResourceManager.GetString("Clear_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        public static string Close_big {
            get {
                return ResourceManager.GetString("Close_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close_small {
            get {
                return ResourceManager.GetString("Close_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string Delete_big {
            get {
                return ResourceManager.GetString("Delete_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_small {
            get {
                return ResourceManager.GetString("Delete_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dine Time.
        /// </summary>
        public static string DineTime {
            get {
                return ResourceManager.GetString("DineTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        public static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Activity.
        /// </summary>
        public static string EditActivity {
            get {
                return ResourceManager.GetString("EditActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Activity Category.
        /// </summary>
        public static string EditActivityCategory {
            get {
                return ResourceManager.GetString("EditActivityCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Allergy.
        /// </summary>
        public static string EditAllergy {
            get {
                return ResourceManager.GetString("EditAllergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Building.
        /// </summary>
        public static string EditBuilding {
            get {
                return ResourceManager.GetString("EditBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Suite.
        /// </summary>
        public static string EditSuite {
            get {
                return ResourceManager.GetString("EditSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Venue.
        /// </summary>
        public static string EditVenue {
            get {
                return ResourceManager.GetString("EditVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext.
        /// </summary>
        public static string Ext {
            get {
                return ResourceManager.GetString("Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor No.
        /// </summary>
        public static string FloorNo {
            get {
                return ResourceManager.GetString("FloorNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fun Picture.
        /// </summary>
        public static string FunPicture {
            get {
                return ResourceManager.GetString("FunPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home (Name).
        /// </summary>
        public static string Home_Name {
            get {
                return ResourceManager.GetString("Home_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Image.
        /// </summary>
        public static string HomeImage {
            get {
                return ResourceManager.GetString("HomeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homes.
        /// </summary>
        public static string Homes {
            get {
                return ResourceManager.GetString("Homes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivite User.
        /// </summary>
        public static string InactiviteUser {
            get {
                return ResourceManager.GetString("InactiviteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        public static string Lunch {
            get {
                return ResourceManager.GetString("Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masters.
        /// </summary>
        public static string Masters {
            get {
                return ResourceManager.GetString("Masters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Seniors Care Living Centres.
        /// </summary>
        public static string MasterSupport1 {
            get {
                return ResourceManager.GetString("MasterSupport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 175 Bloor Street East, Suite 601, South Tower.
        /// </summary>
        public static string MasterSupport2 {
            get {
                return ResourceManager.GetString("MasterSupport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toronto, Ontario, M4W 3R8.
        /// </summary>
        public static string MasterSupport3 {
            get {
                return ResourceManager.GetString("MasterSupport3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 416-323-3773 ext. 373.
        /// </summary>
        public static string MasterSupport4 {
            get {
                return ResourceManager.GetString("MasterSupport4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Care Color.
        /// </summary>
        public static string MemoryCareColor {
            get {
                return ResourceManager.GetString("MemoryCareColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (English).
        /// </summary>
        public static string Name_en {
            get {
                return ResourceManager.GetString("Name_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (French).
        /// </summary>
        public static string Name_fr {
            get {
                return ResourceManager.GetString("Name_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Floor.
        /// </summary>
        public static string numberofFloor {
            get {
                return ResourceManager.GetString("numberofFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Rooms.
        /// </summary>
        public static string numberofRooms {
            get {
                return ResourceManager.GetString("numberofRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Suites.
        /// </summary>
        public static string numberofSuites {
            get {
                return ResourceManager.GetString("numberofSuites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone (Home).
        /// </summary>
        public static string Phone_home {
            get {
                return ResourceManager.GetString("Phone_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone (Mobile).
        /// </summary>
        public static string Phone_mobile {
            get {
                return ResourceManager.GetString("Phone_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone (Work).
        /// </summary>
        public static string Phone_work {
            get {
                return ResourceManager.GetString("Phone_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Homes.
        /// </summary>
        public static string ProvinceHomes {
            get {
                return ResourceManager.GetString("ProvinceHomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string Save_big {
            get {
                return ResourceManager.GetString("Save_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save_small {
            get {
                return ResourceManager.GetString("Save_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for.
        /// </summary>
        public static string Searchfor {
            get {
                return ResourceManager.GetString("Searchfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Province.
        /// </summary>
        public static string SelectProvince {
            get {
                return ResourceManager.GetString("SelectProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show This In Assessment.
        /// </summary>
        public static string ShowThisInAssessment {
            get {
                return ResourceManager.GetString("ShowThisInAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/N.
        /// </summary>
        public static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Diet.
        /// </summary>
        public static string SpecialDiet {
            get {
                return ResourceManager.GetString("SpecialDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        public static string Submit_big {
            get {
                return ResourceManager.GetString("Submit_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit_small {
            get {
                return ResourceManager.GetString("Submit_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suite.
        /// </summary>
        public static string Suite {
            get {
                return ResourceManager.GetString("Suite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suite No.
        /// </summary>
        public static string SuiteNo {
            get {
                return ResourceManager.GetString("SuiteNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        public static string Update_big {
            get {
                return ResourceManager.GetString("Update_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update_small {
            get {
                return ResourceManager.GetString("Update_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        public static string Venue {
            get {
                return ResourceManager.GetString("Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
