//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class test_qolaEntities : DbContext
    {
        public test_qolaEntities()
            : base("name=test_qolaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppSetting> AppSettings { get; set; }
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Activity> tbl_Activity { get; set; }
        public virtual DbSet<tbl_Activity_Calendar_Names> tbl_Activity_Calendar_Names { get; set; }
        public virtual DbSet<tbl_Activity_Category> tbl_Activity_Category { get; set; }
        public virtual DbSet<tbl_Activity_Display_Name> tbl_Activity_Display_Name { get; set; }
        public virtual DbSet<tbl_Activity_Event_Attendance> tbl_Activity_Event_Attendance { get; set; }
        public virtual DbSet<tbl_Activity_Events> tbl_Activity_Events { get; set; }
        public virtual DbSet<tbl_Administer_Medication> tbl_Administer_Medication { get; set; }
        public virtual DbSet<tbl_Allergy> tbl_Allergy { get; set; }
        public virtual DbSet<tbl_Bathing_Attendance> tbl_Bathing_Attendance { get; set; }
        public virtual DbSet<tbl_Care_Plan_P2> tbl_Care_Plan_P2 { get; set; }
        public virtual DbSet<tbl_Care_Plan_P2_Details> tbl_Care_Plan_P2_Details { get; set; }
        public virtual DbSet<tbl_Careplan_P2_Category> tbl_Careplan_P2_Category { get; set; }
        public virtual DbSet<tbl_Careplan_P2_Subcategory> tbl_Careplan_P2_Subcategory { get; set; }
        public virtual DbSet<tbl_Daily_Reports> tbl_Daily_Reports { get; set; }
        public virtual DbSet<tbl_Dementia_CheckList> tbl_Dementia_CheckList { get; set; }
        public virtual DbSet<tbl_Dementia_Questions> tbl_Dementia_Questions { get; set; }
        public virtual DbSet<tbl_Dietary_Assessment> tbl_Dietary_Assessment { get; set; }
        public virtual DbSet<tbl_Dine_Attendance> tbl_Dine_Attendance { get; set; }
        public virtual DbSet<tbl_Dine_Time> tbl_Dine_Time { get; set; }
        public virtual DbSet<tbl_Direction> tbl_Direction { get; set; }
        public virtual DbSet<tbl_Doctor_Appointment> tbl_Doctor_Appointment { get; set; }
        public virtual DbSet<tbl_Doctor_Apppoinment_History> tbl_Doctor_Apppoinment_History { get; set; }
        public virtual DbSet<tbl_Doctor_Resident_Communication> tbl_Doctor_Resident_Communication { get; set; }
        public virtual DbSet<tbl_Drug> tbl_Drug { get; set; }
        public virtual DbSet<tbl_emar_Additional_Option_Select> tbl_emar_Additional_Option_Select { get; set; }
        public virtual DbSet<tbl_emar_Additional_Options> tbl_emar_Additional_Options { get; set; }
        public virtual DbSet<tbl_Emar_Allergy> tbl_Emar_Allergy { get; set; }
        public virtual DbSet<tbl_Emar_Audit_Trail> tbl_Emar_Audit_Trail { get; set; }
        public virtual DbSet<tbl_emar_Controlled_Drug_Schedule> tbl_emar_Controlled_Drug_Schedule { get; set; }
        public virtual DbSet<tbl_emar_Diet> tbl_emar_Diet { get; set; }
        public virtual DbSet<tbl_Emar_Erx> tbl_Emar_Erx { get; set; }
        public virtual DbSet<tbl_emar_Follow_Up_Note> tbl_emar_Follow_Up_Note { get; set; }
        public virtual DbSet<tbl_emar_Frequency> tbl_emar_Frequency { get; set; }
        public virtual DbSet<tbl_emar_Kroll_Order> tbl_emar_Kroll_Order { get; set; }
        public virtual DbSet<tbl_emar_KrollDocs> tbl_emar_KrollDocs { get; set; }
        public virtual DbSet<tbl_Emar_KrollHomes> tbl_Emar_KrollHomes { get; set; }
        public virtual DbSet<tbl_Emar_KrollPatients> tbl_Emar_KrollPatients { get; set; }
        public virtual DbSet<tbl_Emar_KrollRxs> tbl_Emar_KrollRxs { get; set; }
        public virtual DbSet<tbl_Emar_MARTAR_Frequency_CustomCycle> tbl_Emar_MARTAR_Frequency_CustomCycle { get; set; }
        public virtual DbSet<tbl_emar_Medical_Directives> tbl_emar_Medical_Directives { get; set; }
        public virtual DbSet<tbl_Emar_MedicalCondition> tbl_Emar_MedicalCondition { get; set; }
        public virtual DbSet<tbl_emar_Medication_Order> tbl_emar_Medication_Order { get; set; }
        public virtual DbSet<tbl_emar_Medication_Order_MARTAR> tbl_emar_Medication_Order_MARTAR { get; set; }
        public virtual DbSet<tbl_emar_Medication_Order_MARTAR_Frequency> tbl_emar_Medication_Order_MARTAR_Frequency { get; set; }
        public virtual DbSet<tbl_emar_Medication_Order_temp> tbl_emar_Medication_Order_temp { get; set; }
        public virtual DbSet<tbl_emar_Nursing_Wards> tbl_emar_Nursing_Wards { get; set; }
        public virtual DbSet<tbl_emar_Pass_Time> tbl_emar_Pass_Time { get; set; }
        public virtual DbSet<tbl_emar_Patient_as_Store_Kroll> tbl_emar_Patient_as_Store_Kroll { get; set; }
        public virtual DbSet<tbl_emar_Physician_Order_Type> tbl_emar_Physician_Order_Type { get; set; }
        public virtual DbSet<tbl_emar_Prescription_Admin> tbl_emar_Prescription_Admin { get; set; }
        public virtual DbSet<tbl_emar_Prescription_Discontinue> tbl_emar_Prescription_Discontinue { get; set; }
        public virtual DbSet<tbl_emar_Prescription_Discontinue_Kroll> tbl_emar_Prescription_Discontinue_Kroll { get; set; }
        public virtual DbSet<tbl_emar_Prescription_Hold> tbl_emar_Prescription_Hold { get; set; }
        public virtual DbSet<tbl_Emar_Prescription_Hold_Kroll> tbl_Emar_Prescription_Hold_Kroll { get; set; }
        public virtual DbSet<tbl_emar_Prescription_Inventory> tbl_emar_Prescription_Inventory { get; set; }
        public virtual DbSet<tbl_Emar_Prescription_LOA> tbl_Emar_Prescription_LOA { get; set; }
        public virtual DbSet<tbl_emar_Prescription_Remove_From_MAR> tbl_emar_Prescription_Remove_From_MAR { get; set; }
        public virtual DbSet<tbl_emar_Prescription_Reorder> tbl_emar_Prescription_Reorder { get; set; }
        public virtual DbSet<tbl_emar_Resident_Local_Stock> tbl_emar_Resident_Local_Stock { get; set; }
        public virtual DbSet<tbl_emar_Resident_Vital_Signs> tbl_emar_Resident_Vital_Signs { get; set; }
        public virtual DbSet<tbl_emar_Resident_Vital_Signs_Prescription> tbl_emar_Resident_Vital_Signs_Prescription { get; set; }
        public virtual DbSet<tbl_emar_Resident_Vital_Signs_Prescription_Frequency> tbl_emar_Resident_Vital_Signs_Prescription_Frequency { get; set; }
        public virtual DbSet<tbl_emar_Resident_Vital_Signs_Prescription_FrequencyDropdownValue> tbl_emar_Resident_Vital_Signs_Prescription_FrequencyDropdownValue { get; set; }
        public virtual DbSet<tbl_emar_Resident_Vital_Signs_Prescription_RxLink> tbl_emar_Resident_Vital_Signs_Prescription_RxLink { get; set; }
        public virtual DbSet<tbl_Emar_Sig> tbl_Emar_Sig { get; set; }
        public virtual DbSet<tbl_Emar_Topical_Admin> tbl_Emar_Topical_Admin { get; set; }
        public virtual DbSet<tbl_emar_Waste_Dosage_Order> tbl_emar_Waste_Dosage_Order { get; set; }
        public virtual DbSet<tbl_Fall_Risk_Assessment> tbl_Fall_Risk_Assessment { get; set; }
        public virtual DbSet<tbl_Food> tbl_Food { get; set; }
        public virtual DbSet<tbl_Food_Connecting_Word> tbl_Food_Connecting_Word { get; set; }
        public virtual DbSet<tbl_Form> tbl_Form { get; set; }
        public virtual DbSet<tbl_Goal_Sheet> tbl_Goal_Sheet { get; set; }
        public virtual DbSet<tbl_Goal_Sheet_Details> tbl_Goal_Sheet_Details { get; set; }
        public virtual DbSet<tbl_Goal_Sheet_Follow_Up> tbl_Goal_Sheet_Follow_Up { get; set; }
        public virtual DbSet<tbl_Home> tbl_Home { get; set; }
        public virtual DbSet<tbl_Immunization> tbl_Immunization { get; set; }
        public virtual DbSet<tbl_Initial_Activity_Assessment> tbl_Initial_Activity_Assessment { get; set; }
        public virtual DbSet<tbl_Meal_Calendar> tbl_Meal_Calendar { get; set; }
        public virtual DbSet<tbl_Meal_Planner> tbl_Meal_Planner { get; set; }
        public virtual DbSet<tbl_Meal_Planner_Menu> tbl_Meal_Planner_Menu { get; set; }
        public virtual DbSet<tbl_Medication> tbl_Medication { get; set; }
        public virtual DbSet<tbl_Medication_Detail> tbl_Medication_Detail { get; set; }
        public virtual DbSet<tbl_Pass_Times> tbl_Pass_Times { get; set; }
        public virtual DbSet<tbl_Plan_Of_Care> tbl_Plan_Of_Care { get; set; }
        public virtual DbSet<tbl_PostfallClinicalMonitoringDetails> tbl_PostfallClinicalMonitoringDetails { get; set; }
        public virtual DbSet<tbl_PostfallClinicalMonitoringVitalSigns> tbl_PostfallClinicalMonitoringVitalSigns { get; set; }
        public virtual DbSet<tbl_Prescription> tbl_Prescription { get; set; }
        public virtual DbSet<tbl_Progress_Notes> tbl_Progress_Notes { get; set; }
        public virtual DbSet<tbl_Province> tbl_Province { get; set; }
        public virtual DbSet<tbl_Resident> tbl_Resident { get; set; }
        public virtual DbSet<tbl_Resident_Away_Schedule> tbl_Resident_Away_Schedule { get; set; }
        public virtual DbSet<tbl_Resident_Diet_Allergy> tbl_Resident_Diet_Allergy { get; set; }
        public virtual DbSet<tbl_Resident_Medical_Allergy> tbl_Resident_Medical_Allergy { get; set; }
        public virtual DbSet<tbl_Resident_Profile_Image> tbl_Resident_Profile_Image { get; set; }
        public virtual DbSet<tbl_Resident_Satisfaction_Survey> tbl_Resident_Satisfaction_Survey { get; set; }
        public virtual DbSet<tbl_Resident_Satisfaction_Survey_Category> tbl_Resident_Satisfaction_Survey_Category { get; set; }
        public virtual DbSet<tbl_Resident_Satisfaction_Survey_Question> tbl_Resident_Satisfaction_Survey_Question { get; set; }
        public virtual DbSet<tbl_Resident_Satisfaction_Survey_Response> tbl_Resident_Satisfaction_Survey_Response { get; set; }
        public virtual DbSet<tbl_Resident_Special_Diet> tbl_Resident_Special_Diet { get; set; }
        public virtual DbSet<tbl_Resident_Temp> tbl_Resident_Temp { get; set; }
        public virtual DbSet<tbl_Resident_Track_Record> tbl_Resident_Track_Record { get; set; }
        public virtual DbSet<tbl_SpecialDiet> tbl_SpecialDiet { get; set; }
        public virtual DbSet<tbl_Suite> tbl_Suite { get; set; }
        public virtual DbSet<tbl_Suite_Handler> tbl_Suite_Handler { get; set; }
        public virtual DbSet<tbl_Suite_Handler_Status> tbl_Suite_Handler_Status { get; set; }
        public virtual DbSet<tbl_Suite_Handler_Temp> tbl_Suite_Handler_Temp { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_User_IP_MAC> tbl_User_IP_MAC { get; set; }
        public virtual DbSet<tbl_Venue> tbl_Venue { get; set; }
        public virtual DbSet<tbl_Version> tbl_Version { get; set; }
        public virtual DbSet<tbl_Activity_20150131> tbl_Activity_20150131 { get; set; }
        public virtual DbSet<tbl_Activity_Category_20150131> tbl_Activity_Category_20150131 { get; set; }
        public virtual DbSet<tbl_Activity_Event_Attendance_20150131> tbl_Activity_Event_Attendance_20150131 { get; set; }
        public virtual DbSet<tbl_Activity_Events_20150131> tbl_Activity_Events_20150131 { get; set; }
        public virtual DbSet<tbl_Administer_Medication_Old> tbl_Administer_Medication_Old { get; set; }
        public virtual DbSet<tbl_emar_Drug> tbl_emar_Drug { get; set; }
        public virtual DbSet<tbl_Initial_Activity_Assessment_20150131> tbl_Initial_Activity_Assessment_20150131 { get; set; }
        public virtual DbSet<tbl_Prescription_Details> tbl_Prescription_Details { get; set; }
        public virtual DbSet<tbl_Progress_Notes_Acknowledgement> tbl_Progress_Notes_Acknowledgement { get; set; }
        public virtual DbSet<tbl_User_Type> tbl_User_Type { get; set; }
        public virtual DbSet<tbl_postfallclinicalmonitoringBpage2> tbl_postfallclinicalmonitoringBpage2 { get; set; }
    }
}
