//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emar_Resident_Vital_Signs_Prescription_FrequencyDropdownValue
    {
        public int ID { get; set; }
        public string Frequency { get; set; }
        public string Type { get; set; }
        public Nullable<int> NumberOfTime { get; set; }
    }
}
