//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Daily_Reports
    {
        public int fd_id { get; set; }
        public int fd_home_id { get; set; }
        public Nullable<int> fd_suite_census { get; set; }
        public Nullable<int> fd_suite_perm { get; set; }
        public Nullable<int> fd_suite_temp { get; set; }
        public string fd_suite_notice { get; set; }
        public Nullable<int> fd_suite_capacity { get; set; }
        public Nullable<System.DateTime> fd_date { get; set; }
        public string fd_perm_suite_rented { get; set; }
        public string fd_on_deposit { get; set; }
        public string fd_suite_left_to_fill { get; set; }
        public string fd_outstating_receivable { get; set; }
        public string fd_daily_bank_deposit { get; set; }
        public string fd_suite_breakdown_applicable { get; set; }
        public string fd_tours { get; set; }
        public string fd_marketing { get; set; }
        public string fd_notice { get; set; }
        public string fd_hospital_updates { get; set; }
        public string fd_nurse_report { get; set; }
        public Nullable<int> fd_second_person { get; set; }
        public string fd_advertising { get; set; }
        public string fd_key_operating { get; set; }
        public string fd_neysas_deficiency_list { get; set; }
        public int fd_modified_by { get; set; }
        public System.DateTime fd_modified_on { get; set; }
    
        public virtual tbl_Home tbl_Home { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
