//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Prescription_Details
    {
        public int fd_prescription_id { get; set; }
        public string fd_status { get; set; }
        public System.DateTime fd_status_date { get; set; }
        public string fd_status_note { get; set; }
        public int fd_created_by { get; set; }
        public System.DateTime fd_created_on { get; set; }
    
        public virtual tbl_Prescription tbl_Prescription { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
