//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Goal_Sheet_Follow_Up
    {
        public int fd_id { get; set; }
        public int fd_goal_sheet_detail_id { get; set; }
        public string fd_follow_up_note { get; set; }
        public string fd_close_type { get; set; }
        public Nullable<System.DateTime> fd_close_date { get; set; }
        public string fd_reminder { get; set; }
        public Nullable<System.DateTime> fd_reminder_date { get; set; }
        public int fd_created_by { get; set; }
        public System.DateTime fd_created_on { get; set; }
    
        public virtual tbl_Goal_Sheet_Details tbl_Goal_Sheet_Details { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
