//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emar_Prescription_Inventory
    {
        public int Id { get; set; }
        public int PrescriptionId { get; set; }
        public Nullable<int> OnHand { get; set; }
        public Nullable<int> Destroyed { get; set; }
        public Nullable<int> CarriedNextOrder { get; set; }
        public Nullable<int> FromPrevOrder { get; set; }
        public string Reason { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
