//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emar_Physician_Order_Type
    {
        public int Id { get; set; }
        public int HomeId { get; set; }
        public string Value { get; set; }
        public byte Type { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual tbl_Home tbl_Home { get; set; }
    }
}
