//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Goal_Sheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Goal_Sheet()
        {
            this.tbl_Goal_Sheet_Details = new HashSet<tbl_Goal_Sheet_Details>();
        }
    
        public int fd_id { get; set; }
        public int fd_resident_id { get; set; }
        public System.DateTime fd_date { get; set; }
        public string fd_resident_needs { get; set; }
        public string fd_intervention { get; set; }
        public string fd_effectiveness { get; set; }
        public int fd_modified_by { get; set; }
        public System.DateTime fd_modified_on { get; set; }
        public Nullable<System.DateTime> fd_resolved_date { get; set; }
        public int fd_created_by { get; set; }
        public System.DateTime fd_created_on { get; set; }
        public Nullable<byte> fd_services { get; set; }
        public Nullable<byte> fd_category_type { get; set; }
        public string fd_service_other { get; set; }
        public string fd_point_of_contact { get; set; }
        public string fd_closed_type { get; set; }
        public Nullable<int> fd_point_of_contact_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Goal_Sheet_Details> tbl_Goal_Sheet_Details { get; set; }
        public virtual tbl_Resident tbl_Resident { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
