//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Emar_Prescription_Hold_Kroll
    {
        public int Id { get; set; }
        public Nullable<int> KrollSuspendId { get; set; }
        public Nullable<int> EmarOrderId { get; set; }
        public Nullable<System.DateTime> SuspendDate { get; set; }
        public Nullable<System.DateTime> ResumeDate { get; set; }
    }
}
