//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Resident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Resident()
        {
            this.tbl_Care_Plan_P2 = new HashSet<tbl_Care_Plan_P2>();
            this.tbl_Dementia_CheckList = new HashSet<tbl_Dementia_CheckList>();
            this.tbl_Dietary_Assessment = new HashSet<tbl_Dietary_Assessment>();
            this.tbl_Doctor_Apppoinment_History = new HashSet<tbl_Doctor_Apppoinment_History>();
            this.tbl_Doctor_Resident_Communication = new HashSet<tbl_Doctor_Resident_Communication>();
            this.tbl_Fall_Risk_Assessment = new HashSet<tbl_Fall_Risk_Assessment>();
            this.tbl_Goal_Sheet = new HashSet<tbl_Goal_Sheet>();
            this.tbl_Initial_Activity_Assessment = new HashSet<tbl_Initial_Activity_Assessment>();
            this.tbl_Medication = new HashSet<tbl_Medication>();
            this.tbl_Plan_Of_Care = new HashSet<tbl_Plan_Of_Care>();
            this.tbl_Prescription = new HashSet<tbl_Prescription>();
            this.tbl_Progress_Notes = new HashSet<tbl_Progress_Notes>();
            this.tbl_Resident_Away_Schedule = new HashSet<tbl_Resident_Away_Schedule>();
            this.tbl_Resident_Medical_Allergy = new HashSet<tbl_Resident_Medical_Allergy>();
            this.tbl_Resident_Profile_Image = new HashSet<tbl_Resident_Profile_Image>();
            this.tbl_Resident_Satisfaction_Survey = new HashSet<tbl_Resident_Satisfaction_Survey>();
            this.tbl_Resident_Track_Record = new HashSet<tbl_Resident_Track_Record>();
            this.tbl_Suite_Handler = new HashSet<tbl_Suite_Handler>();
        }
    
        public int fd_id { get; set; }
        public int fd_home_id { get; set; }
        public string fd_suite_id { get; set; }
        public string fd_first_name { get; set; }
        public string fd_last_name { get; set; }
        public string fd_gender { get; set; }
        public System.DateTime fd_move_in_date { get; set; }
        public Nullable<System.DateTime> fd_move_out_date { get; set; }
        public Nullable<byte> fd_occupancy { get; set; }
        public string fd_phone { get; set; }
        public System.DateTime fd_birth_date { get; set; }
        public string fd_MB_health_number { get; set; }
        public string fd_insurance_company { get; set; }
        public string fd_contract_number { get; set; }
        public string fd_group_number { get; set; }
        public string fd_contact_1 { get; set; }
        public string fd_address_1 { get; set; }
        public string fd_relationship_1 { get; set; }
        public string fd_home_phone_1 { get; set; }
        public string fd_business_phone_1 { get; set; }
        public string fd_cell_phone_1 { get; set; }
        public string fd_email_1 { get; set; }
        public string fd_contact_2 { get; set; }
        public string fd_address_2 { get; set; }
        public string fd_relationship_2 { get; set; }
        public string fd_home_phone_2 { get; set; }
        public string fd_business_phone_2 { get; set; }
        public string fd_cell_phone_2 { get; set; }
        public string fd_email_2 { get; set; }
        public string fd_contact_3 { get; set; }
        public string fd_address_3 { get; set; }
        public string fd_relationship_3 { get; set; }
        public string fd_home_phone_3 { get; set; }
        public string fd_business_phone_3 { get; set; }
        public string fd_cell_phone_3 { get; set; }
        public string fd_email_3 { get; set; }
        public string fd_POA_care { get; set; }
        public string fd_care_home_phone_no { get; set; }
        public string fd_physician { get; set; }
        public string fd_physician_phone { get; set; }
        public string fd_alergies { get; set; }
        public string fd_health_history { get; set; }
        public string fd_assess_frequency { get; set; }
        public string fd_status { get; set; }
        public int fd_modified_by { get; set; }
        public System.DateTime fd_modified_on { get; set; }
        public string fd_birth_place { get; set; }
        public byte fd_marital_status { get; set; }
        public string fd_significat_other { get; set; }
        public string fd_relationship_family { get; set; }
        public string fd_registered_voter { get; set; }
        public string fd_veteran { get; set; }
        public string fd_religious_affiliation { get; set; }
        public string fd_personal_involvement { get; set; }
        public string fd_education_level { get; set; }
        public string fd_ability_to_read { get; set; }
        public string fd_ability_to_write { get; set; }
        public string fd_other_language { get; set; }
        public string fd_past_occupations_jobs { get; set; }
        public Nullable<int> fd_hand_dominance { get; set; }
        public string fd_image { get; set; }
        public string fd_care_work_phone_no { get; set; }
        public string fd_care_email { get; set; }
        public string fd_POA_finance { get; set; }
        public string fd_finance_home_phone_no { get; set; }
        public string fd_finance_work_phone_no { get; set; }
        public string fd_finance_email { get; set; }
        public Nullable<System.DateTime> fd_admitted_from { get; set; }
        public string fd_care_address { get; set; }
        public string fd_care_relationship { get; set; }
        public Nullable<byte> fd_care_type { get; set; }
        public string fd_finance_address { get; set; }
        public string fd_finance_relationship { get; set; }
        public string fd_DNR { get; set; }
        public string fd_full_code { get; set; }
        public string fd_funeral_argument { get; set; }
        public string fd_pharmacy_self { get; set; }
        public string fd_pharmacy_nursing { get; set; }
        public string fd_pharmacy_fax_no { get; set; }
        public string fd_pharmacy_phone_no { get; set; }
        public string fd_religion_contact { get; set; }
        public string fd_religion_home_phone { get; set; }
        public string fd_religon_office { get; set; }
        public string fd_qola_resident { get; set; }
        public string fd_call_hospital { get; set; }
        public string fd_contact_1_password { get; set; }
        public string fd_contact_2_password { get; set; }
        public string fd_contact_3_password { get; set; }
        public string fd_short_name { get; set; }
        public string fd_physician_fax_no { get; set; }
        public string fd_DNR_status { get; set; }
        public string fd_fullcode_status { get; set; }
        public Nullable<byte> fd_read_type { get; set; }
        public Nullable<byte> fd_write_type { get; set; }
        public string fd_voter_type { get; set; }
        public string fd_veteran_type { get; set; }
        public Nullable<byte> fd_education_type { get; set; }
        public Nullable<System.DateTime> fd_aniversary_date { get; set; }
        public Nullable<byte> fd_religious_affiliation_type { get; set; }
        public Nullable<byte> fd_profile_type { get; set; }
        public System.Guid fd_GUID { get; set; }
        public string fd_current_diagnoses { get; set; }
        public Nullable<byte> fd_home_phone_type_1 { get; set; }
        public Nullable<byte> fd_business_phone_type_1 { get; set; }
        public Nullable<byte> fd_cell_phone_type_1 { get; set; }
        public Nullable<byte> fd_home_phone_type_2 { get; set; }
        public Nullable<byte> fd_business_phone_type_2 { get; set; }
        public Nullable<byte> fd_cell_phone_type_2 { get; set; }
        public Nullable<byte> fd_home_phone_type_3 { get; set; }
        public Nullable<byte> fd_business_phone_type_3 { get; set; }
        public Nullable<byte> fd_cell_phone_type_3 { get; set; }
        public Nullable<byte> fd_POA_care_type { get; set; }
        public string fd_POA_care_type_status { get; set; }
        public Nullable<byte> fd_POA_finance_type { get; set; }
        public string fd_POA_finance_type_status { get; set; }
        public string fd_POA_care_cell_no { get; set; }
        public string fd_POA_finance_cell_no { get; set; }
        public Nullable<byte> fd_POA_care_home_type { get; set; }
        public Nullable<byte> fd_POA_care_business_type { get; set; }
        public Nullable<byte> fd_POA_care_cell_type { get; set; }
        public Nullable<byte> fd_POA_finance_home_type { get; set; }
        public Nullable<byte> fd_POA_finance_business_type { get; set; }
        public Nullable<byte> fd_POA_finance_cell_type { get; set; }
        public string fd_cultural_preferences { get; set; }
        public string fd_POA_care_type_2_status { get; set; }
        public string fd_POA_care_type_3_status { get; set; }
        public string fd_POA_finance_type_2_status { get; set; }
        public string fd_POA_finance_type_3_status { get; set; }
        public string fd_Favourite_song { get; set; }
        public string fd_Favourite_movie { get; set; }
        public string fd_Number_of_children { get; set; }
        public string fd_Number_of_grandchildren { get; set; }
        public string fd_Favourite_dessert { get; set; }
        public string fd_Favourite_drink { get; set; }
        public string fd_Favourite_flower { get; set; }
        public string fd_Favourite_pets { get; set; }
        public string fd_Wakeup_time { get; set; }
        public string fd_Go_to_bed_at { get; set; }
        public string fd_Favourite_past_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Care_Plan_P2> tbl_Care_Plan_P2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Dementia_CheckList> tbl_Dementia_CheckList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Dietary_Assessment> tbl_Dietary_Assessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Doctor_Apppoinment_History> tbl_Doctor_Apppoinment_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Doctor_Resident_Communication> tbl_Doctor_Resident_Communication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Fall_Risk_Assessment> tbl_Fall_Risk_Assessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Goal_Sheet> tbl_Goal_Sheet { get; set; }
        public virtual tbl_Home tbl_Home { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Initial_Activity_Assessment> tbl_Initial_Activity_Assessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Medication> tbl_Medication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Plan_Of_Care> tbl_Plan_Of_Care { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Prescription> tbl_Prescription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Progress_Notes> tbl_Progress_Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resident_Away_Schedule> tbl_Resident_Away_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resident_Medical_Allergy> tbl_Resident_Medical_Allergy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resident_Profile_Image> tbl_Resident_Profile_Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resident_Satisfaction_Survey> tbl_Resident_Satisfaction_Survey { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resident_Track_Record> tbl_Resident_Track_Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Suite_Handler> tbl_Suite_Handler { get; set; }
    }
}
