//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emar_Resident_Local_Stock
    {
        public int Id { get; set; }
        public Nullable<int> HomeId { get; set; }
        public Nullable<int> DrugId { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<decimal> OnHand { get; set; }
        public Nullable<decimal> Minimum { get; set; }
        public Nullable<decimal> Maximum { get; set; }
        public Nullable<decimal> OrderPack { get; set; }
        public Nullable<decimal> CarriedToNext { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<int> ReceivedStatus { get; set; }
    }
}
