//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Dietary_Assessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Dietary_Assessment()
        {
            this.tbl_Resident_Diet_Allergy = new HashSet<tbl_Resident_Diet_Allergy>();
            this.tbl_Resident_Special_Diet = new HashSet<tbl_Resident_Special_Diet>();
        }
    
        public int fd_id { get; set; }
        public int fd_resident_id { get; set; }
        public int fd_sl_no { get; set; }
        public string fd_special_diat { get; set; }
        public string fd_allergy { get; set; }
        public string fd_likes { get; set; }
        public string fd_dislikes { get; set; }
        public int fd_modified_by { get; set; }
        public System.DateTime fd_modified_on { get; set; }
        public string fd_nutritional { get; set; }
        public string fd_appetite { get; set; }
        public string fd_risk_assistive_device { get; set; }
        public string fd_nutrition { get; set; }
        public string fd_nutrition_diet_other { get; set; }
        public string fd_nutrition_texture { get; set; }
        public string fd_nutrition_diet_note { get; set; }
        public string fd_view { get; set; }
        public Nullable<int> fd_viewed_by { get; set; }
        public Nullable<System.DateTime> fd_viewed_on { get; set; }
        public string fd_known_allergy { get; set; }
        public string fd_nutrition_different { get; set; }
    
        public virtual tbl_Resident tbl_Resident { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resident_Diet_Allergy> tbl_Resident_Diet_Allergy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resident_Special_Diet> tbl_Resident_Special_Diet { get; set; }
    }
}
