//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Medication_Detail
    {
        public int fd_id { get; set; }
        public int fd_medication_id { get; set; }
        public short fd_sl_no { get; set; }
        public int fd_drug_id { get; set; }
        public string fd_dosage { get; set; }
        public string fd_purpose { get; set; }
        public string fd_timings { get; set; }
        public Nullable<System.DateTime> fd_date { get; set; }
        public Nullable<int> fd_original_RX { get; set; }
    
        public virtual tbl_Drug tbl_Drug { get; set; }
        public virtual tbl_Medication tbl_Medication { get; set; }
    }
}
