//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Progress_Notes_Acknowledgement
    {
        public int fd_id { get; set; }
        public System.DateTime fd_date { get; set; }
        public int fd_progress_notes_id { get; set; }
        public int fd_user_id { get; set; }
    
        public virtual tbl_Progress_Notes tbl_Progress_Notes { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
