//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PostfallClinicalMonitoringVitalSigns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PostfallClinicalMonitoringVitalSigns()
        {
            this.tbl_PostfallClinicalMonitoringDetails = new HashSet<tbl_PostfallClinicalMonitoringDetails>();
        }
    
        public int Id { get; set; }
        public string residentid { get; set; }
        public string vitalsign { get; set; }
        public string date_created { get; set; }
        public string category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PostfallClinicalMonitoringDetails> tbl_PostfallClinicalMonitoringDetails { get; set; }
    }
}
