//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Resident_Track_Record
    {
        public long fd_id { get; set; }
        public byte fd_category_id { get; set; }
        public int fd_referance_id { get; set; }
        public int fd_home_id { get; set; }
        public int fd_resident_id { get; set; }
        public System.DateTime fd_date_time { get; set; }
        public string fd_title { get; set; }
        public string fd_description { get; set; }
        public int fd_created_by { get; set; }
        public System.DateTime fd_created_on { get; set; }
        public string fd_attendance { get; set; }
        public string fd_progress_note { get; set; }
    
        public virtual tbl_Home tbl_Home { get; set; }
        public virtual tbl_Resident tbl_Resident { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
