//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emar_Kroll_Order
    {
        public int Id { get; set; }
        public Nullable<int> EmarRxId { get; set; }
        public string EmarRxNumber { get; set; }
        public Nullable<int> ErxId { get; set; }
        public Nullable<int> ToDoId { get; set; }
        public Nullable<int> RxId { get; set; }
        public Nullable<int> KrollRxNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> NewEmarRxId { get; set; }
        public Nullable<int> ErxOrderId { get; set; }
    }
}
