//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Immunization
    {
        public int fd_id { get; set; }
        public int fd_planeofcare_id { get; set; }
        public Nullable<System.DateTime> fd_pheumovax { get; set; }
        public Nullable<System.DateTime> fd_flu_vaccine { get; set; }
        public Nullable<System.DateTime> fd_mantoux { get; set; }
        public Nullable<System.DateTime> fd_chest_Xray { get; set; }
        public Nullable<System.DateTime> fd_tetanus { get; set; }
        public string fd_BP_value { get; set; }
        public Nullable<System.DateTime> fd_BP_date { get; set; }
        public Nullable<byte> fd_pulse_value { get; set; }
        public Nullable<System.DateTime> fd_pulse_date { get; set; }
        public Nullable<double> fd_weight_value { get; set; }
        public Nullable<System.DateTime> fd_weight_date { get; set; }
        public Nullable<double> fd_height_value { get; set; }
        public Nullable<System.DateTime> fd_height_date { get; set; }
        public Nullable<System.DateTime> fd_MRSA_diagnosed { get; set; }
        public Nullable<System.DateTime> fd_MRSA_resolved { get; set; }
        public Nullable<System.DateTime> fd_VRE_diagnosed { get; set; }
        public Nullable<System.DateTime> fd_VRE_resolved { get; set; }
        public string fd_others { get; set; }
        public string fd_consultants { get; set; }
        public Nullable<System.DateTime> fd_pheumovax_due_date { get; set; }
        public Nullable<System.DateTime> fd_flu_vaccine_due_date { get; set; }
        public Nullable<System.DateTime> fd_mantoux_due_date { get; set; }
        public Nullable<System.DateTime> fd_chest_Xray_due_date { get; set; }
        public Nullable<System.DateTime> fd_tetanus_due_date { get; set; }
        public string fd_consults_specialist1 { get; set; }
        public Nullable<System.DateTime> fd_consults_specialist1_date { get; set; }
        public string fd_consults_specialist2 { get; set; }
        public Nullable<System.DateTime> fd_consults_specialist2_date { get; set; }
        public string fd_consults_specialist3 { get; set; }
        public Nullable<System.DateTime> fd_consults_specialist3_date { get; set; }
        public Nullable<byte> fd_weight_measurement { get; set; }
        public Nullable<byte> fd_height_measurement { get; set; }
        public string fd_immunization { get; set; }
        public Nullable<System.DateTime> fd_Cdiff_diagnosed { get; set; }
        public Nullable<System.DateTime> fd_Cdiff_resolved { get; set; }
        public Nullable<byte> fd_BP_systolic { get; set; }
        public Nullable<decimal> fd_temperature { get; set; }
        public Nullable<System.DateTime> fd_temperature_date { get; set; }
        public Nullable<System.DateTime> fd_other_diagnosed { get; set; }
        public Nullable<System.DateTime> fd_other_resolved { get; set; }
        public string fd_infection_others { get; set; }
    
        public virtual tbl_Plan_Of_Care tbl_Plan_Of_Care { get; set; }
    }
}
