//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Activity_Display_Name
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Activity_Display_Name()
        {
            this.tbl_Activity_Events = new HashSet<tbl_Activity_Events>();
        }
    
        public int fd_id { get; set; }
        public int fd_activity_id { get; set; }
        public string fd_name { get; set; }
        public string fd_status { get; set; }
        public Nullable<int> fd_approved_by { get; set; }
        public Nullable<System.DateTime> fd_approved_on { get; set; }
        public int fd_created_by { get; set; }
        public System.DateTime fd_created_on { get; set; }
        public Nullable<int> fd_modified_by { get; set; }
        public Nullable<System.DateTime> fd_modified_on { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Activity_Events> tbl_Activity_Events { get; set; }
    }
}
