//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emar_Resident_Vital_Signs_Prescription
    {
        public int ID { get; set; }
        public int HomeID { get; set; }
        public int ResidentID { get; set; }
        public string VitalType { get; set; }
        public Nullable<decimal> TypeValue { get; set; }
        public int ValueStatus { get; set; }
        public string Notes { get; set; }
        public int Vital_Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> BackCreatedDate { get; set; }
        public Nullable<int> CopyNote { get; set; }
        public Nullable<decimal> TypeValue2 { get; set; }
    }
}
