//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emar_Patient_as_Store_Kroll
    {
        public int Id { get; set; }
        public Nullable<int> HomeId { get; set; }
        public Nullable<int> KrollRxId { get; set; }
        public Nullable<int> KrollPatId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> KrollRxNumber { get; set; }
        public Nullable<int> DrugId { get; set; }
        public string Direction { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> HandledDate { get; set; }
        public Nullable<int> HandledStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
