//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Emar_Audit_Trail
    {
        public int ID { get; set; }
        public Nullable<int> HomeID { get; set; }
        public int UserID { get; set; }
        public string Audit { get; set; }
        public string ObjectType { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
