//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Resident_Medical_Allergy
    {
        public int fd_resident_id { get; set; }
        public int fd_allergy_id { get; set; }
        public string fd_note { get; set; }
        public Nullable<System.DateTime> fd_effective_from { get; set; }
        public Nullable<System.DateTime> fd_effective_to { get; set; }
    
        public virtual tbl_Allergy tbl_Allergy { get; set; }
        public virtual tbl_Resident tbl_Resident { get; set; }
    }
}
