//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Meal_Calendar
    {
        public int fd_id { get; set; }
        public int fd_home_id { get; set; }
        public System.DateTime fd_from_date { get; set; }
        public System.DateTime fd_to_date { get; set; }
        public int fd_meal_planner_id { get; set; }
        public string fd_name { get; set; }
        public string fd_notes { get; set; }
        public string fd_previous_meal_planner { get; set; }
        public int fd_modified_by { get; set; }
        public System.DateTime fd_modified_on { get; set; }
        public byte fd_type { get; set; }
    
        public virtual tbl_Home tbl_Home { get; set; }
        public virtual tbl_Meal_Planner tbl_Meal_Planner { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
