//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emar_Drug
    {
        public int ID { get; set; }
        public Nullable<int> KrollDrgID { get; set; }
        public string BrandName { get; set; }
        public string GenericName { get; set; }
        public string DIN { get; set; }
        public string Manufacturer { get; set; }
        public string ManufacturerAbbreviation { get; set; }
        public string Description { get; set; }
        public string Form { get; set; }
        public string FormAbbreviation { get; set; }
        public string Strength { get; set; }
        public Nullable<bool> Package { get; set; }
        public string Schedule { get; set; }
        public Nullable<bool> Reportable { get; set; }
        public string DefaultSig { get; set; }
        public Nullable<int> PriceGroupId { get; set; }
        public Nullable<bool> PriceGroupIdSpecified { get; set; }
        public Nullable<int> ExpiryDays { get; set; }
        public Nullable<bool> ExpiryDaysSpecified { get; set; }
        public Nullable<byte> FollowupDays { get; set; }
        public Nullable<bool> FollowupDaysSpecified { get; set; }
        public string AutoDispLocation { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> DateCreatedSpecified { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public Nullable<bool> DateChangedSpecified { get; set; }
        public string EquivTo { get; set; }
        public string OralWritten { get; set; }
        public Nullable<int> SubstituteDrgId { get; set; }
        public Nullable<bool> SubstituteDrgIdSpecified { get; set; }
        public Nullable<bool> PrintCompliance { get; set; }
        public Nullable<bool> IsTrial { get; set; }
        public string FirstDrugName { get; set; }
        public string SecondDrugName { get; set; }
        public Nullable<bool> IsWardStock { get; set; }
        public Nullable<bool> IsNarcotic { get; set; }
        public Nullable<bool> IsControlled { get; set; }
        public Nullable<bool> IsFlavorRx { get; set; }
        public Nullable<bool> HalfSizeSig { get; set; }
        public Nullable<int> CentralMaintFieldMask { get; set; }
        public Nullable<int> CentralMaintFieldMask2 { get; set; }
        public Nullable<int> InterchangeablePriority { get; set; }
        public Nullable<bool> InterchangeablePrioritySpecified { get; set; }
        public string BrandGenericType { get; set; }
        public string TADin { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<bool> DepartmentIdSpecified { get; set; }
        public Nullable<int> DrugMessageId { get; set; }
        public Nullable<bool> DrugMessageIdSpecified { get; set; }
        public Nullable<bool> EligibleForCoupon { get; set; }
        public Nullable<bool> IsDevice { get; set; }
        public string FeeForServiceType { get; set; }
        public Nullable<bool> IsImmunization { get; set; }
        public string DinType { get; set; }
        public Nullable<int> DrgFormId { get; set; }
        public Nullable<bool> DrgFormIdSpecified { get; set; }
        public string FDBRouteCode { get; set; }
        public Nullable<int> MergedToId { get; set; }
        public Nullable<bool> MergedToIdSpecified { get; set; }
        public string HandlingInstructions { get; set; }
        public string Description2 { get; set; }
        public Nullable<int> CentralMaintOverrideFieldMask { get; set; }
        public Nullable<int> CentralMaintAllowOverrideFieldMask { get; set; }
        public Nullable<int> CentralMaintOverrideFieldMask2 { get; set; }
        public Nullable<int> CentralMaintAllowOverrideFieldMask2 { get; set; }
        public Nullable<int> ShapeId { get; set; }
        public Nullable<bool> ShapeIdSpecified { get; set; }
        public Nullable<int> ColourId1 { get; set; }
        public Nullable<bool> ColourId1Specified { get; set; }
        public Nullable<int> ColourId2 { get; set; }
        public Nullable<bool> ColourId2Specified { get; set; }
        public string Markings1 { get; set; }
        public string Markings2 { get; set; }
        public Nullable<bool> RequireLotNumWhenPackaging { get; set; }
        public Nullable<bool> RequireExpiryDateWhenPackaging { get; set; }
        public Nullable<bool> Refrigerated { get; set; }
        public string Picture { get; set; }
        public Nullable<decimal> PackSize { get; set; }
    }
}
