//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Resident_Temp
    {
        public int fd_id { get; set; }
        public int fd_home_id { get; set; }
        public string fd_suite_id { get; set; }
        public string fd_first_name { get; set; }
        public string fd_last_name { get; set; }
        public string fd_gender { get; set; }
        public System.DateTime fd_move_in_date { get; set; }
        public Nullable<System.DateTime> fd_move_out_date { get; set; }
        public Nullable<byte> fd_occupancy { get; set; }
        public string fd_phone { get; set; }
        public System.DateTime fd_birth_date { get; set; }
        public string fd_MB_health_number { get; set; }
        public string fd_insurance_company { get; set; }
        public string fd_contract_number { get; set; }
        public string fd_group_number { get; set; }
        public string fd_contact_1 { get; set; }
        public string fd_address_1 { get; set; }
        public string fd_relationship_1 { get; set; }
        public string fd_home_phone_1 { get; set; }
        public string fd_business_phone_1 { get; set; }
        public string fd_cell_phone_1 { get; set; }
        public string fd_email_1 { get; set; }
        public string fd_contact_2 { get; set; }
        public string fd_address_2 { get; set; }
        public string fd_relationship_2 { get; set; }
        public string fd_home_phone_2 { get; set; }
        public string fd_business_phone_2 { get; set; }
        public string fd_cell_phone_2 { get; set; }
        public string fd_email_2 { get; set; }
        public string fd_contact_3 { get; set; }
        public string fd_address_3 { get; set; }
        public string fd_relationship_3 { get; set; }
        public string fd_home_phone_3 { get; set; }
        public string fd_business_phone_3 { get; set; }
        public string fd_cell_phone_3 { get; set; }
        public string fd_email_3 { get; set; }
        public string fd_POA_care { get; set; }
        public string fd_care_home_phone_no { get; set; }
        public string fd_physician { get; set; }
        public string fd_physician_phone { get; set; }
        public string fd_alergies { get; set; }
        public string fd_health_history { get; set; }
        public string fd_assess_frequency { get; set; }
        public string fd_status { get; set; }
        public int fd_modified_by { get; set; }
        public System.DateTime fd_modified_on { get; set; }
        public string fd_birth_place { get; set; }
        public byte fd_marital_status { get; set; }
        public string fd_significat_other { get; set; }
        public string fd_relationship_family { get; set; }
        public string fd_registered_voter { get; set; }
        public string fd_veteran { get; set; }
        public string fd_religious_affiliation { get; set; }
        public string fd_personal_involvement { get; set; }
        public string fd_education_level { get; set; }
        public string fd_ability_to_read { get; set; }
        public string fd_ability_to_write { get; set; }
        public string fd_other_language { get; set; }
        public string fd_past_occupations_jobs { get; set; }
        public Nullable<int> fd_hand_dominance { get; set; }
        public string fd_image { get; set; }
        public string fd_care_work_phone_no { get; set; }
        public string fd_care_email { get; set; }
        public string fd_POA_finance { get; set; }
        public string fd_finance_home_phone_no { get; set; }
        public string fd_finance_work_phone_no { get; set; }
        public string fd_finance_email { get; set; }
        public Nullable<System.DateTime> fd_admitted_from { get; set; }
        public string fd_care_address { get; set; }
        public string fd_care_relationship { get; set; }
        public Nullable<byte> fd_care_type { get; set; }
        public string fd_finance_address { get; set; }
        public string fd_finance_relationship { get; set; }
        public string fd_DNR { get; set; }
        public string fd_full_code { get; set; }
        public string fd_funeral_argument { get; set; }
        public string fd_pharmacy_self { get; set; }
        public string fd_pharmacy_nursing { get; set; }
        public string fd_pharmacy_fax_no { get; set; }
        public string fd_pharmacy_phone_no { get; set; }
        public string fd_religion_contact { get; set; }
        public string fd_religion_home_phone { get; set; }
        public string fd_religon_office { get; set; }
        public string fd_qola_resident { get; set; }
        public string fd_call_hospital { get; set; }
        public string fd_short_name { get; set; }
        public string fd_contact_1_password { get; set; }
        public string fd_contact_2_password { get; set; }
        public string fd_contact_3_password { get; set; }
        public string fd_physician_fax_no { get; set; }
        public string fd_DNR_status { get; set; }
        public string fd_fullcode_status { get; set; }
        public Nullable<System.DateTime> fd_aniversary_date { get; set; }
        public Nullable<byte> fd_religious_affiliation_type { get; set; }
        public Nullable<byte> fd_read_type { get; set; }
        public Nullable<byte> fd_write_type { get; set; }
        public string fd_voter_type { get; set; }
        public string fd_veteran_type { get; set; }
        public Nullable<byte> fd_education_type { get; set; }
        public Nullable<byte> fd_profile_type { get; set; }
        public System.Guid fd_GUID { get; set; }
        public string fd_current_diagnoses { get; set; }
        public Nullable<byte> fd_home_phone_type_1 { get; set; }
        public Nullable<byte> fd_business_phone_type_1 { get; set; }
        public Nullable<byte> fd_cell_phone_type_1 { get; set; }
        public Nullable<byte> fd_home_phone_type_2 { get; set; }
        public Nullable<byte> fd_business_phone_type_2 { get; set; }
        public Nullable<byte> fd_cell_phone_type_2 { get; set; }
        public Nullable<byte> fd_home_phone_type_3 { get; set; }
        public Nullable<byte> fd_business_phone_type_3 { get; set; }
        public Nullable<byte> fd_cell_phone_type_3 { get; set; }
        public Nullable<byte> fd_POA_care_type { get; set; }
        public string fd_POA_care_type_status { get; set; }
        public Nullable<byte> fd_POA_finance_type { get; set; }
        public string fd_POA_finance_type_status { get; set; }
        public string fd_POA_care_cell_no { get; set; }
        public string fd_POA_finance_cell_no { get; set; }
        public Nullable<byte> fd_POA_care_home_type { get; set; }
        public Nullable<byte> fd_POA_care_business_type { get; set; }
        public Nullable<byte> fd_POA_care_cell_type { get; set; }
        public Nullable<byte> fd_POA_finance_home_type { get; set; }
        public Nullable<byte> fd_POA_finance_business_type { get; set; }
        public Nullable<byte> fd_POA_finance_cell_type { get; set; }
        public string fd_cultural_preferences { get; set; }
        public string fd_POA_care_type_2_status { get; set; }
        public string fd_POA_care_type_3_status { get; set; }
        public string fd_POA_finance_type_2_status { get; set; }
        public string fd_POA_finance_type_3_status { get; set; }
    }
}
