//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emar_Follow_Up_Note
    {
        public int Id { get; set; }
        public int PrescriptionId { get; set; }
        public System.DateTime AdministerTime { get; set; }
        public string MedicationNote { get; set; }
        public Nullable<System.DateTime> MedicationDate { get; set; }
        public string FollowUpNote { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public int Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
