//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Resident_Satisfaction_Survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Resident_Satisfaction_Survey()
        {
            this.tbl_Resident_Satisfaction_Survey_Response = new HashSet<tbl_Resident_Satisfaction_Survey_Response>();
        }
    
        public int fd_id { get; set; }
        public int fd_resident_id { get; set; }
        public string fd_completed_by { get; set; }
        public string fd_specify { get; set; }
        public string fd_relation_ship { get; set; }
        public System.DateTime fd_date { get; set; }
        public string fd_survey_completed_status { get; set; }
        public int fd_created_by { get; set; }
        public System.DateTime fd_created_on { get; set; }
        public int fd_modified_by { get; set; }
        public System.DateTime fd_modified_on { get; set; }
    
        public virtual tbl_Resident tbl_Resident { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resident_Satisfaction_Survey_Response> tbl_Resident_Satisfaction_Survey_Response { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_User tbl_User1 { get; set; }
    }
}
