//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User_IP_MAC
    {
        public int fd_id { get; set; }
        public int fd_user_id { get; set; }
        public string fd_type { get; set; }
        public string fd_name { get; set; }
        public string fd_value { get; set; }
        public string fd_status { get; set; }
        public int fd_sort_order { get; set; }
        public int fd_modified_by { get; set; }
        public System.DateTime fd_modified_on { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_User tbl_User1 { get; set; }
    }
}
