//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Plan_Of_Care
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Plan_Of_Care()
        {
            this.tbl_Immunization = new HashSet<tbl_Immunization>();
        }
    
        public int fd_id { get; set; }
        public int fd_resident_id { get; set; }
        public string fd_physician { get; set; }
        public System.DateTime fd_date { get; set; }
        public string fd_assessed { get; set; }
        public string fd_appetite { get; set; }
        public string fd_nutrition { get; set; }
        public string fd_nutrition_SDR { get; set; }
        public string fd_nutrition_FAS { get; set; }
        public string fd_elimination_bladder { get; set; }
        public string fd_elimination_B_incontinence { get; set; }
        public string fd_elimination_bowel { get; set; }
        public string fd_elimination_ostomy { get; set; }
        public string fd_elimination_managed { get; set; }
        public string fd_mobility { get; set; }
        public string fd_mobility_prothesis { get; set; }
        public string fd_mobility_concerns { get; set; }
        public string fd_personal_hygiene_appropriate { get; set; }
        public string fd_personal_hygiene { get; set; }
        public string fd_PH_bathing_time { get; set; }
        public string fd_PH_bathing_frequency { get; set; }
        public string fd_PH_service { get; set; }
        public string fd_PH_service_agency { get; set; }
        public string fd_special_needs { get; set; }
        public string fd_SN_O2_supplier { get; set; }
        public string fd_SN_O2_rate { get; set; }
        public string fd_SN_other { get; set; }
        public string fd_SN_comments { get; set; }
        public string fd_SA_vision { get; set; }
        public string fd_SA_vision_comments { get; set; }
        public string fd_SA_hearing { get; set; }
        public string fd_cognitive_function { get; set; }
        public string fd_behaviour { get; set; }
        public string fd_behaviour_comments { get; set; }
        public string fd_communication { get; set; }
        public string fd_communication_comments { get; set; }
        public string fd_smoking { get; set; }
        public string fd_alcohol { get; set; }
        public Nullable<decimal> fd_alcohol_amt { get; set; }
        public string fd_AD_abuse { get; set; }
        public string fd_activities { get; set; }
        public string fd_medication_administration { get; set; }
        public string fd_MA_pharmacy { get; set; }
        public string fd_MA_injections { get; set; }
        public string fd_advanced_directive_completed { get; set; }
        public string fd_wound_care { get; set; }
        public string fd_WC_agency_servicing { get; set; }
        public string fd_WC_comments { get; set; }
        public string fd_family_meeting { get; set; }
        public int fd_modified_by { get; set; }
        public System.DateTime fd_modified_on { get; set; }
        public string fd_bladder_toileting { get; set; }
        public string fd_bladder_comment { get; set; }
        public string fd_bowel_toileting { get; set; }
        public string fd_bowel_comment { get; set; }
        public string fd_mobility_comment { get; set; }
        public string fd_walker_type { get; set; }
        public string fd_wheelchair_type { get; set; }
        public string fd_cane_type { get; set; }
        public string fd_scooter_type { get; set; }
        public string fd_transfers_comment { get; set; }
        public string fd_skin_care_comment { get; set; }
        public string fd_toileting { get; set; }
        public string fd_continence_comment { get; set; }
        public string fd_eating { get; set; }
        public string fd_eating_on_unit { get; set; }
        public string fd_eating_main_dr { get; set; }
        public string fd_eating_breakfast { get; set; }
        public string fd_eating_lunch { get; set; }
        public string fd_eating_dinner { get; set; }
        public string fd_nutritional { get; set; }
        public string fd_describe { get; set; }
        public string fd_nutritional_reg { get; set; }
        public string fd_nutritional_minced { get; set; }
        public string fd_nutritional_purced { get; set; }
        public string fd_nutritional_comment { get; set; }
        public string fd_alert_secured_unit { get; set; }
        public string fd_alert_wanderer { get; set; }
        public string fd_alert_unsafe_smoker { get; set; }
        public string fd_alert_substance_abuse { get; set; }
        public string fd_alert_seizures { get; set; }
        public string fd_alert_diabetic { get; set; }
        public string fd_alert_pacemaker { get; set; }
        public string fd_alert_resist_to_care { get; set; }
        public string fd_alert_choking_risk { get; set; }
        public string fd_alert_comment { get; set; }
        public string fd_restraints_physical_type { get; set; }
        public string fd_restraints_frequency { get; set; }
        public string fd_restraints_environemental { get; set; }
        public string fd_restraints_elopement { get; set; }
        public string fd_restraints_check_hourly { get; set; }
        public string fd_restraints_reposition { get; set; }
        public Nullable<System.DateTime> fd_restraints_rxdate { get; set; }
        public string fd_memory { get; set; }
        public string fd_safety_pasd { get; set; }
        public string fd_safety_pasd_other { get; set; }
        public string fd_language_spoken { get; set; }
        public string fd_SE_pendant { get; set; }
        public string fd_SE_ted_stocking { get; set; }
        public string fd_SE_support_brace { get; set; }
        public string fd_SE_others { get; set; }
        public string fd_LOC_total_care { get; set; }
        public string fd_LOC_partial_assist { get; set; }
        public string fd_LOC_independent { get; set; }
        public string fd_news_paper { get; set; }
        public string fd_laundry { get; set; }
        public string fd_CCAC { get; set; }
        public string fd_OT_physio { get; set; }
        public string fd_OT_program_started { get; set; }
        public string fd_OT_weekly_scheduled { get; set; }
        public string fd_PT_program_started { get; set; }
        public string fd_PT_weekly_scheduled { get; set; }
        public string fd_recreation_programs { get; set; }
        public string fd_activity_preferences { get; set; }
        public string fd_exercise_group { get; set; }
        public string fd_spiritual { get; set; }
        public string fd_spiritual_phone { get; set; }
        public string fd_family { get; set; }
        public string fd_family_involvement_comment { get; set; }
        public string fd_family_counselling_comment { get; set; }
        public Nullable<byte> fd_alcohol_unit { get; set; }
        public string fd_special_alerts { get; set; }
        public string fd_safty_pasd_comment { get; set; }
        public string fd_spceial_equipment { get; set; }
        public string fd_level_of_care { get; set; }
        public string fd_OT_PT { get; set; }
        public string fd_special_alert_comment { get; set; }
        public string fd_nutrition_diet { get; set; }
        public string fd_nutrition_allergies { get; set; }
        public string fd_nutrition_allergy_note { get; set; }
        public string fd_nutrition_diet_note { get; set; }
        public string fd_AM_agency_name { get; set; }
        public string fd_PM_agency_name { get; set; }
        public string fd_bathing_agency_name { get; set; }
        public string fd_PT_frequency { get; set; }
        public string fd_OT_frequency { get; set; }
        public string fd_continence_Name { get; set; }
        public string fd_continence_assistive_device { get; set; }
        public string fd_continence_supplier { get; set; }
        public Nullable<System.DateTime> fd_continence_date { get; set; }
        public string fd_continence_completed_by { get; set; }
        public string fd_medication_Pharmacy { get; set; }
        public string fd_wound_agency { get; set; }
        public string fd_skincare_treatment { get; set; }
        public string fd_WC_assists { get; set; }
        public string fd_risk_assistive_device { get; set; }
        public Nullable<System.DateTime> fd_AM_preferred_time { get; set; }
        public Nullable<System.DateTime> fd_PM_preferred_time { get; set; }
        public Nullable<System.DateTime> fd_bathing_preferred_time { get; set; }
        public string fd_nutrition_texture { get; set; }
        public string fd_nutrition_diet_other { get; set; }
        public string fd_nutrition_note { get; set; }
        public string fd_SE_details { get; set; }
        public string fd_pt_provider { get; set; }
        public string fd_ot_provider { get; set; }
        public string fd_o2_note { get; set; }
        public string fd_stroke { get; set; }
        public string fd_stroke_note { get; set; }
        public string fd_complete_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Immunization> tbl_Immunization { get; set; }
        public virtual tbl_Resident tbl_Resident { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
