//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Activity()
        {
            this.tbl_Activity_Events = new HashSet<tbl_Activity_Events>();
        }
    
        public int fd_id { get; set; }
        public int fd_activity_category_id { get; set; }
        public string fd_name { get; set; }
        public string fd_color { get; set; }
        public string fd_icon_path { get; set; }
        public string fd_description { get; set; }
        public string fd_status { get; set; }
        public int fd_modified_by { get; set; }
        public System.DateTime fd_modified_on { get; set; }
        public string fd_show_in_assessment { get; set; }
        public Nullable<int> fd_province_id { get; set; }
        public string fd_name_fr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Activity_Events> tbl_Activity_Events { get; set; }
        public virtual tbl_Activity_Category tbl_Activity_Category { get; set; }
        public virtual tbl_Province tbl_Province { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
