//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Administer_Medication
    {
        public int fd_id { get; set; }
        public int fd_medication_detail_id { get; set; }
        public string fd_timing { get; set; }
        public byte fd_status { get; set; }
        public string fd_site { get; set; }
        public Nullable<byte> fd_pulse_rate { get; set; }
        public Nullable<byte> fd_hbp { get; set; }
        public Nullable<byte> fd_lbp { get; set; }
        public int fd_modified_by { get; set; }
        public System.DateTime fd_modified_on { get; set; }
        public string fd_reason { get; set; }
        public Nullable<bool> fd_effective { get; set; }
    
        public virtual tbl_Prescription tbl_Prescription { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
