//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emar_Nursing_Wards
    {
        public int ID { get; set; }
        public int Home_Id { get; set; }
        public Nullable<int> Floor_Number { get; set; }
        public string Floor_Name { get; set; }
        public string Floor_suite_no { get; set; }
    }
}
