//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Progress_Notes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Progress_Notes()
        {
            this.tbl_Progress_Notes_Acknowledgement = new HashSet<tbl_Progress_Notes_Acknowledgement>();
        }
    
        public int fd_id { get; set; }
        public int fd_resident_id { get; set; }
        public System.DateTime fd_date { get; set; }
        public string fd_title { get; set; }
        public string fd_note { get; set; }
        public string fd_status { get; set; }
        public int fd_modified_by { get; set; }
        public System.DateTime fd_modified_on { get; set; }
        public Nullable<byte> fd_category { get; set; }
        public Nullable<byte> fd_remain_in { get; set; }
        public Nullable<int> fd_acknowledged_by { get; set; }
        public Nullable<System.DateTime> fd_acknowledged_on { get; set; }
        public string fd_action_note { get; set; }
        public string fd_fall_date_type { get; set; }
        public Nullable<System.DateTime> fd_fall_date { get; set; }
        public string fd_location { get; set; }
        public string fd_witness_type { get; set; }
        public string fd_witness_fall { get; set; }
        public string fd_Un_witnes_type { get; set; }
        public string fd_incident_report { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Progress_Notes_Acknowledgement> tbl_Progress_Notes_Acknowledgement { get; set; }
        public virtual tbl_Resident tbl_Resident { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
