//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Home
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Home()
        {
            this.tbl_Activity_Events = new HashSet<tbl_Activity_Events>();
            this.tbl_Bathing_Attendance = new HashSet<tbl_Bathing_Attendance>();
            this.tbl_Daily_Reports = new HashSet<tbl_Daily_Reports>();
            this.tbl_Dine_Attendance = new HashSet<tbl_Dine_Attendance>();
            this.tbl_Doctor_Appointment = new HashSet<tbl_Doctor_Appointment>();
            this.tbl_Doctor_Apppoinment_History = new HashSet<tbl_Doctor_Apppoinment_History>();
            this.tbl_Doctor_Resident_Communication = new HashSet<tbl_Doctor_Resident_Communication>();
            this.tbl_emar_Additional_Option_Select = new HashSet<tbl_emar_Additional_Option_Select>();
            this.tbl_emar_Controlled_Drug_Schedule = new HashSet<tbl_emar_Controlled_Drug_Schedule>();
            this.tbl_emar_Frequency = new HashSet<tbl_emar_Frequency>();
            this.tbl_emar_Pass_Time = new HashSet<tbl_emar_Pass_Time>();
            this.tbl_emar_Physician_Order_Type = new HashSet<tbl_emar_Physician_Order_Type>();
            this.tbl_Meal_Calendar = new HashSet<tbl_Meal_Calendar>();
            this.tbl_Meal_Planner = new HashSet<tbl_Meal_Planner>();
            this.tbl_Resident_Away_Schedule = new HashSet<tbl_Resident_Away_Schedule>();
            this.tbl_Resident_Profile_Image = new HashSet<tbl_Resident_Profile_Image>();
            this.tbl_Resident = new HashSet<tbl_Resident>();
            this.tbl_Resident_Track_Record = new HashSet<tbl_Resident_Track_Record>();
            this.tbl_Suite_Handler = new HashSet<tbl_Suite_Handler>();
            this.tbl_Suite = new HashSet<tbl_Suite>();
            this.tbl_Venue = new HashSet<tbl_Venue>();
        }
    
        public int fd_id { get; set; }
        public string fd_name { get; set; }
        public string fd_code { get; set; }
        public string fd_address { get; set; }
        public string fd_city { get; set; }
        public int fd_province { get; set; }
        public string fd_postal_code { get; set; }
        public string fd_country { get; set; }
        public byte fd_no_of_floor { get; set; }
        public short fd_no_of_suites { get; set; }
        public string fd_icon_image { get; set; }
        public string fd_status { get; set; }
        public int fd_modified_by { get; set; }
        public System.DateTime fd_modified_on { get; set; }
        public string fd_dine_time_Ids { get; set; }
        public string fd_phone { get; set; }
        public System.Guid fd_GUID { get; set; }
        public string fd_pass_time_Ids { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Activity_Events> tbl_Activity_Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Bathing_Attendance> tbl_Bathing_Attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Daily_Reports> tbl_Daily_Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Dine_Attendance> tbl_Dine_Attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Doctor_Appointment> tbl_Doctor_Appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Doctor_Apppoinment_History> tbl_Doctor_Apppoinment_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Doctor_Resident_Communication> tbl_Doctor_Resident_Communication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_emar_Additional_Option_Select> tbl_emar_Additional_Option_Select { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_emar_Controlled_Drug_Schedule> tbl_emar_Controlled_Drug_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_emar_Frequency> tbl_emar_Frequency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_emar_Pass_Time> tbl_emar_Pass_Time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_emar_Physician_Order_Type> tbl_emar_Physician_Order_Type { get; set; }
        public virtual tbl_Province tbl_Province { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Meal_Calendar> tbl_Meal_Calendar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Meal_Planner> tbl_Meal_Planner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resident_Away_Schedule> tbl_Resident_Away_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resident_Profile_Image> tbl_Resident_Profile_Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resident> tbl_Resident { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resident_Track_Record> tbl_Resident_Track_Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Suite_Handler> tbl_Suite_Handler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Suite> tbl_Suite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Venue> tbl_Venue { get; set; }
    }
}
