//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Activity_Events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Activity_Events()
        {
            this.tbl_Activity_Event_Attendance = new HashSet<tbl_Activity_Event_Attendance>();
        }
    
        public int fd_id { get; set; }
        public int fd_home_id { get; set; }
        public int fd_activity_id { get; set; }
        public System.DateTime fd_date { get; set; }
        public int fd_venue_id { get; set; }
        public string fd_note { get; set; }
        public string fd_previous_month_activity { get; set; }
        public int fd_modified_by { get; set; }
        public System.DateTime fd_modified_on { get; set; }
        public string fd_sign_up { get; set; }
        public byte fd_type { get; set; }
        public Nullable<int> fd_activity_display_name_id { get; set; }
        public Nullable<bool> fd_out_break { get; set; }
    
        public virtual tbl_Activity tbl_Activity { get; set; }
        public virtual tbl_Activity_Display_Name tbl_Activity_Display_Name { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Activity_Event_Attendance> tbl_Activity_Event_Attendance { get; set; }
        public virtual tbl_Home tbl_Home { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
