//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emar_Medical_Directives
    {
        public int Id { get; set; }
        public int HomeId { get; set; }
        public int DrugId { get; set; }
        public Nullable<decimal> DoseAmount { get; set; }
        public string DoseUnit { get; set; }
        public string RouteOfAdministration { get; set; }
        public string Directions { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SigCode { get; set; }
        public Nullable<int> SigForm { get; set; }
    }
}
