//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Activity_20150131
    {
        public int fd_id { get; set; }
        public int fd_activity_category_id { get; set; }
        public string fd_name { get; set; }
        public string fd_color { get; set; }
        public string fd_icon_path { get; set; }
        public string fd_description { get; set; }
        public string fd_status { get; set; }
        public int fd_modified_by { get; set; }
        public System.DateTime fd_modified_on { get; set; }
        public string fd_show_in_assessment { get; set; }
        public Nullable<int> fd_province_id { get; set; }
    }
}
