//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_postfallclinicalmonitoringBpage2
    {
        public int Id { get; set; }
        public string longsounds { get; set; }
        public string longsoundsdescribe { get; set; }
        public string longsoundsequal { get; set; }
        public string chest { get; set; }
        public string chestother { get; set; }
        public string heartsounds { get; set; }
        public string heartsoundsdescribe { get; set; }
        public string soft { get; set; }
        public string softdescribe { get; set; }
        public string painful { get; set; }
        public string painfuldescribe { get; set; }
        public string bowelsoundsheard { get; set; }
        public string lastbowelmovement { get; set; }
        public string voiding { get; set; }
        public string voidingdesciption { get; set; }
        public string voidingincontinentpadsused { get; set; }
        public string voidingiscontinent { get; set; }
        public string voidingiscather { get; set; }
        public string edmafeet { get; set; }
        public string edmafeetdescription { get; set; }
        public string edmafeetposition { get; set; }
        public string hands { get; set; }
        public string handsdescription { get; set; }
        public string handsposition { get; set; }
        public string handsother { get; set; }
        public string handsotherdescription { get; set; }
        public string skinfeet { get; set; }
        public string skinfeetdescription { get; set; }
        public string rashes { get; set; }
        public string redness { get; set; }
        public string bruising { get; set; }
        public string openareas { get; set; }
        public string wound { get; set; }
        public string wonddescription { get; set; }
        public string residentishavingpain { get; set; }
        public string residentpaindescription { get; set; }
        public string painscale { get; set; }
        public string p_qaching { get; set; }
        public string p_qsharp { get; set; }
        public string p_qdull { get; set; }
        public string p_qradiating { get; set; }
        public string painlocation { get; set; }
        public string painwhatmakesitbetter { get; set; }
        public string painwhatmakesitworse { get; set; }
        public string ispainsurfacewithdl { get; set; }
        public string painother { get; set; }
        public string completedby { get; set; }
        public string date_completed { get; set; }
        public string category { get; set; }
        public string adlsdescription { get; set; }
        public string abnormalareasdescription { get; set; }
        public string residentid { get; set; }
    }
}
