//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC.EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emar_Resident_Vital_Signs_Prescription_Frequency
    {
        public int Id { get; set; }
        public int ResidentID { get; set; }
        public string VitalType { get; set; }
        public Nullable<int> TimeDay { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string Directives { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
