//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QOLAProductionFinalsEntities : DbContext
    {
        public QOLAProductionFinalsEntities()
            : base("name=QOLAProductionFinalsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<new_tbl_suite> new_tbl_suite { get; set; }
    
        public virtual int sp_add_new_tbl_suite(string home, Nullable<int> suite_no, Nullable<int> floor_no, Nullable<int> no_of_rooms)
        {
            var homeParameter = home != null ?
                new ObjectParameter("Home", home) :
                new ObjectParameter("Home", typeof(string));
    
            var suite_noParameter = suite_no.HasValue ?
                new ObjectParameter("suite_no", suite_no) :
                new ObjectParameter("suite_no", typeof(int));
    
            var floor_noParameter = floor_no.HasValue ?
                new ObjectParameter("floor_no", floor_no) :
                new ObjectParameter("floor_no", typeof(int));
    
            var no_of_roomsParameter = no_of_rooms.HasValue ?
                new ObjectParameter("no_of_rooms", no_of_rooms) :
                new ObjectParameter("no_of_rooms", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_new_tbl_suite", homeParameter, suite_noParameter, floor_noParameter, no_of_roomsParameter);
        }
    
        public virtual int sp_delete_new_tbl_suite(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_new_tbl_suite", idParameter);
        }
    
        public virtual ObjectResult<sp_get_new_tbl_suite_Result> sp_get_new_tbl_suite()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_new_tbl_suite_Result>("sp_get_new_tbl_suite");
        }
    
        public virtual int sp_update_new_tbl_suite(string home, Nullable<int> suite_no, Nullable<int> floor_no, Nullable<int> no_of_rooms)
        {
            var homeParameter = home != null ?
                new ObjectParameter("Home", home) :
                new ObjectParameter("Home", typeof(string));
    
            var suite_noParameter = suite_no.HasValue ?
                new ObjectParameter("suite_no", suite_no) :
                new ObjectParameter("suite_no", typeof(int));
    
            var floor_noParameter = floor_no.HasValue ?
                new ObjectParameter("floor_no", floor_no) :
                new ObjectParameter("floor_no", typeof(int));
    
            var no_of_roomsParameter = no_of_rooms.HasValue ?
                new ObjectParameter("no_of_rooms", no_of_rooms) :
                new ObjectParameter("no_of_rooms", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_new_tbl_suite", homeParameter, suite_noParameter, floor_noParameter, no_of_roomsParameter);
        }
    }
}
