//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QolaMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_tbl_suite
    {
        public int id { get; set; }
        public string Home { get; set; }
        public Nullable<int> suite_no { get; set; }
        public Nullable<int> floor_no { get; set; }
        public Nullable<int> no_of_rooms { get; set; }
    }
}
